export const TODO_ADD = 'todo/add'
export const TODO_UPDATE = 'todo/update'
export const TODO_DELETE = 'todo/delete'
export const TODO_DELETE_ALL_DONE = 'todo/deleteAllDone'
export const TODO_CHANGE_ALL_STATUS = 'todo/changeAllStatus'